/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * CloudCost AI API specification
 * OpenAPI spec version: 0.1.0
 */

export * from "./analysisResult";
export * from "./costByType";
export * from "./dashboardData";
export * from "./errorResponse";
export * from "./getResourcesParams";
export * from "./getResourcesPriority";
export * from "./getResourcesType";
export * from "./healthStatus";
export * from "./recommendationsData";
export * from "./recommendedAction";
export * from "./report";
export * from "./reportDetail";
export * from "./resource";
export * from "./resourceEnvironment";
export * from "./resourcePriority";
export * from "./resourceType";
export * from "./savingsByIssue";
export * from "./seedResult";
